# Generated by Django 2.0.7 on 2020-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feautured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
