# Generated by Django 2.0.7 on 2020-06-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200627_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='description',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userform',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
