# Generated by Django 2.0.7 on 2020-06-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_loginform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginform',
            old_name='username',
            new_name='title',
        ),
    ]
