# Generated by Django 2.0.7 on 2020-06-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200628_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginForm',
        ),
    ]
