# Generated by Django 2.0.7 on 2020-06-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200628_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(max_length=5),
        ),
    ]
