# Generated by Django 2.0.7 on 2020-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200628_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='password',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.TextField(max_length=30),
        ),
    ]
