# Generated by Django 2.0.7 on 2020-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200628_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='password',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userform',
            old_name='username',
            new_name='title',
        ),
        migrations.AddField(
            model_name='userform',
            name='feautured',
            field=models.BooleanField(default=True),
        ),
    ]
